language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2

install:
  - 'composer --prefer-dist install'

script:
  - vendor/bin/phpunit -v

after_script:
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.2" ]]; then ./vendor/bin/test-reporter; fi